export default [
  [
    { id: "0.0", face: "JJ" },
    { id: "0.1", face: "2S" },
    { id: "0.2", face: "3S" },
    { id: "0.3", face: "4S" },
    { id: "0.4", face: "5S" },
    { id: "0.5", face: "6S" },
    { id: "0.6", face: "7S" },
    { id: "0.7", face: "8S" },
    { id: "0.8", face: "9S" },
    { id: "0.9", face: "JJ" },
  ],
  [
    { id: "1.0", face: "6C" },
    { id: "1.1", face: "5C" },
    { id: "1.2", face: "4C" },
    { id: "1.3", face: "3C" },
    { id: "1.4", face: "2C" },
    { id: "1.5", face: "AH" },
    { id: "1.6", face: "KH" },
    { id: "1.7", face: "QH" },
    { id: "1.8", face: "TH" },
    { id: "1.9", face: "TS" },
  ],
  [
    { id: "2.0", face: "7C" },
    { id: "2.1", face: "AS" },
    { id: "2.2", face: "2D" },
    { id: "2.3", face: "3D" },
    { id: "2.4", face: "4D" },
    { id: "2.5", face: "5D" },
    { id: "2.6", face: "6D" },
    { id: "2.7", face: "7D" },
    { id: "2.8", face: "9H" },
    { id: "2.9", face: "QS" },
  ],
  [
    { id: "3.0", face: "8C" },
    { id: "3.1", face: "KS" },
    { id: "3.2", face: "6C" },
    { id: "3.3", face: "5C" },
    { id: "3.4", face: "4C" },
    { id: "3.5", face: "3C" },
    { id: "3.6", face: "2C" },
    { id: "3.7", face: "8D" },
    { id: "3.8", face: "8H" },
    { id: "3.9", face: "KS" },
  ],
  [
    { id: "4.0", face: "9C" },
    { id: "4.1", face: "QS" },
    { id: "4.2", face: "7C" },
    { id: "4.3", face: "6H" },
    { id: "4.4", face: "5H" },
    { id: "4.5", face: "4H" },
    { id: "4.6", face: "AH" },
    { id: "4.7", face: "9D" },
    { id: "4.8", face: "7H" },
    { id: "4.9", face: "AS" },
  ],
  [
    { id: "5.0", face: "TC" },
    { id: "5.1", face: "TS" },
    { id: "5.2", face: "8C" },
    { id: "5.3", face: "7H" },
    { id: "5.4", face: "2H" },
    { id: "5.5", face: "3H" },
    { id: "5.6", face: "KH" },
    { id: "5.7", face: "TD" },
    { id: "5.8", face: "6H" },
    { id: "5.9", face: "2D" },
  ],
  [
    { id: "6.0", face: "QC" },
    { id: "6.1", face: "9S" },
    { id: "6.2", face: "9C" },
    { id: "6.3", face: "8H" },
    { id: "6.4", face: "9H" },
    { id: "6.5", face: "TH" },
    { id: "6.6", face: "QH" },
    { id: "6.7", face: "QD" },
    { id: "6.8", face: "5H" },
    { id: "6.9", face: "3D" },
  ],
  [
    { id: "7.0", face: "KC" },
    { id: "7.1", face: "8S" },
    { id: "7.2", face: "TC" },
    { id: "7.3", face: "QC" },
    { id: "7.4", face: "KC" },
    { id: "7.5", face: "AC" },
    { id: "7.6", face: "AD" },
    { id: "7.7", face: "KD" },
    { id: "7.8", face: "4H" },
    { id: "7.9", face: "4D" },
  ],
  [
    { id: "8.0", face: "AC" },
    { id: "8.1", face: "7S" },
    { id: "8.2", face: "6S" },
    { id: "8.3", face: "5S" },
    { id: "8.4", face: "4S" },
    { id: "8.5", face: "3S" },
    { id: "8.6", face: "2S" },
    { id: "8.7", face: "2H" },
    { id: "8.8", face: "3H" },
    { id: "8.9", face: "5D" },
  ],
  [
    { id: "9.0", face: "JJ" },
    { id: "9.1", face: "AD" },
    { id: "9.2", face: "KD" },
    { id: "9.3", face: "QD" },
    { id: "9.4", face: "TD" },
    { id: "9.5", face: "9D" },
    { id: "9.6", face: "8D" },
    { id: "9.7", face: "7D" },
    { id: "9.8", face: "6D" },
    { id: "9.9", face: "JJ" },
  ],
] as const;
